export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOG_OUT = 'LOG_OUT';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Transaction Types
export const ACCOUNT_LOADED = 'ACCOUNT_LOADED';
export const ACCOUNT_LOAD_ERROR = 'ACCOUNT_LOAD_ERROR';
export const TRANSACTION_FAILED = 'TRANSACTION_FAILED';
export const TRANSACTION_SUCCESSFUL = 'TRANSACTION_SUCCESSFUL';
export const BALANCE_UPDATED = 'BALANCE_UPDATED';
export const BALANCE_UPDATE_FAILED = 'BALANCE_UPDATE_FAILED';
export const TRANSACTIONS_LOADED = 'TRANSACTIONS_LOADED';
export const GET_TRANSACTIONS_FAILED = 'GET_TRANSACTIONS_FAILED';
